import { Misconception, MisconceptionId } from '../../types/adaptive';

export const MISCONCEPTIONS: Record<MisconceptionId, Misconception> = {
  AMPLITUDE_VS_PROBABILITY: {
    id: 'AMPLITUDE_VS_PROBABILITY',
    title: 'Confusing Amplitudes with Probabilities',
    category: 'State Fundamentals',
    description: 'Confusing complex probability amplitudes (α, β) with physical measurement probabilities.',
    explanation: 'Probability amplitudes can be complex numbers or negative values (e.g., -1/√2). The probability of measuring a state is the square of the magnitude of its amplitude: P(x) = |α|². Probabilities are always real numbers between 0 and 1.',
    remedy: 'Review Module 1: From Bits to Qubits. Practice squaring amplitudes to calculate measurement probabilities.',
    recommendedModuleId: 'm1',
  },
  SUPERPOSITION_COLLAPSE_CONFUSION: {
    id: 'SUPERPOSITION_COLLAPSE_CONFUSION',
    title: 'Superposition vs Physical State',
    category: 'State Fundamentals',
    description: 'Believing a qubit is literally both 0 and 1 at the same time before measurement.',
    explanation: 'A qubit in superposition is in a definite quantum state |ψ⟩ = α|0⟩ + β|1⟩, not "both 0 and 1 simultaneously". Measurement forces the state to probabilistically collapse into either |0⟩ or |1⟩.',
    remedy: 'Explore Module 1 & Module 3. Observe state vectors before measurement and watch state collapse after measurement.',
    recommendedModuleId: 'm1',
  },
  HADAMARD_ALWAYS_PLUS: {
    id: 'HADAMARD_ALWAYS_PLUS',
    title: 'Assuming H Always Outputs |+⟩',
    category: 'Quantum Gates',
    description: 'Assuming the Hadamard gate always turns any input qubit into the |+⟩ state.',
    explanation: 'The Hadamard gate is unitary and reversible! While H|0⟩ = |+⟩ = (|0⟩+|1⟩)/√2, applying H to |1⟩ yields |−⟩ = (|0⟩-|1⟩)/√2. Crucially, applying H to |+⟩ restores |0⟩, and H|−⟩ restores |1⟩.',
    remedy: 'Work through Module 2: Quantum Gates. Apply the H gate to |1⟩ and |+⟩ to see phase differences.',
    recommendedModuleId: 'm2',
  },
  IGNORING_PHASE: {
    id: 'IGNORING_PHASE',
    title: 'Ignoring Relative Phase',
    category: 'Quantum Gates',
    description: 'Assuming relative phase does not matter because |+⟩ and |−⟩ have identical 50/50 measurement probabilities.',
    explanation: 'Although |+⟩ and |−⟩ both yield 50% probability for |0⟩ and |1⟩, their relative phase differs by π (180°). Applying H to |+⟩ gives |0⟩ (100% 0), while applying H to |−⟩ gives |1⟩ (100% 1). Phase creates constructive or destructive interference!',
    remedy: 'Practice in Module 2 with Z and H gates. See how phase flip transforms outcome when passed through Hadamard.',
    recommendedModuleId: 'm2',
  },
  EXACT_HALF_HALF_SAMPLING: {
    id: 'EXACT_HALF_HALF_SAMPLING',
    title: 'Expecting Exact 50/50 Sampling Ratios',
    category: 'Measurement',
    description: 'Believing finite repeated shots (e.g. 10 shots) must result in exactly 5 0s and 5 1s.',
    explanation: 'Quantum measurement is probabilistic! Like flipping a fair coin 10 times, statistical fluctuations are normal. As shot count increases (e.g. 1,000 shots), empirical frequencies converge to theoretical probabilities by the Law of Large Numbers.',
    remedy: 'Run Module 3: Measurement shots (1, 10, 100, 1000) and compare the histogram frequencies with theoretical probabilities.',
    recommendedModuleId: 'm3',
  },
  ENTANGLEMENT_FTL: {
    id: 'ENTANGLEMENT_FTL',
    title: 'Assuming Entanglement Enables FTL Communication',
    category: 'Entanglement',
    description: 'Thinking measurement of an entangled qubit allows instant faster-than-light data transmission.',
    explanation: 'Measuring one qubit instantly correlates with the other qubit, but the local outcome is completely random (50% 0, 50% 1). No information can be communicated faster than light without a classical signal (No-Communication Theorem).',
    remedy: 'Step through Module 4: Entanglement. Observe why local measurements alone look completely random.',
    recommendedModuleId: 'm4',
  },
  CORRELATION_VS_CAUSATION: {
    id: 'CORRELATION_VS_CAUSATION',
    title: 'Confusing Correlation with Classical Similarity',
    category: 'Entanglement',
    description: 'Treating entangled states as simple independent pairs that happen to share matching classical values.',
    explanation: 'Entangled states (like Bell state (|00⟩+|11⟩)/√2) cannot be factored into product states (|A⟩ ⊗ |B⟩). The system exists as a single unified 2-qubit state vector.',
    remedy: 'Explore Module 4: Entanglement and examine the product state vs Bell state matrix representations.',
    recommendedModuleId: 'm4',
  },
  CNOT_APPLICATION: {
    id: 'CNOT_APPLICATION',
    title: 'Misunderstanding CNOT Gate Control & Target Roles',
    category: 'Quantum Gates & Entanglement',
    description: 'Misidentifying control vs target qubits or assuming CNOT always flips target regardless of control.',
    explanation: 'CNOT only flips the target qubit if the control qubit is in state |1⟩ (or has amplitude in |1⟩). If the control is |0⟩, the target qubit is completely unchanged.',
    remedy: 'Test CNOT with control at |0⟩ vs control at |1⟩ in Module 4 or the Quantum Playground.',
    recommendedModuleId: 'm4',
  },
};
